name: attendance_app
description: A simple attendance app using fingerprint simulation
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Puedes agregar otras dependencias aquí, como el paquete para huellas cuando sea necesario.
